#pragma once

#include "NativeGameplayTags.h"

namespace KilnseedTags
{
	// Plants
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Plant_Aerolume);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Plant_Loamspine);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Plant_Tidefern);

	// Plot states
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Plot_Empty);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Plot_Planted);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Plot_Growing);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Plot_Pollinating);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Plot_Bloomed);

	// Bee roles
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bee_Role_Idle);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bee_Role_Pollinator);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bee_Role_Hydrator);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bee_Role_Harvester);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bee_Role_Planter);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bee_Role_Assembler);

	// Player/world state
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_InSafeZone);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Brownout);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Carrying);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_BuildMode);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	// Milestones
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Milestone_Atmo25);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Milestone_Atmo50);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Milestone_Atmo100);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Milestone_Soil33);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Milestone_Soil66);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Milestone_Soil100);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Milestone_Hydro33);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Milestone_Hydro66);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Milestone_Hydro100);

	// Abilities
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Pickup);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Place);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Harvest);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Pollinate);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Build);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Assemble);

	// Smart Object slots
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmartObject_NeedsPollination);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmartObject_NeedsWater);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmartObject_ReadyToHarvest);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmartObject_NeedsPlanting);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmartObject_NeedsAssembly);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmartObject_SeedSource);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmartObject_WaterSource);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmartObject_DeliveryTarget);

	// Set By Caller data tags (GE magnitudes computed in code)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_GrowthRate);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_WaterDrain);

	// Gameplay Cues
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Harvest);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Deliver);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Milestone);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Pollinate);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Brownout);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_O2Warning);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Death);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Build);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_SafeZone);
}
